name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '16', '18', '19' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: npm install, build, and test
        env:
          CI: true
          LISTEN_ADDR: localhost
        run: |
          npm ci
          npm run build --if-present
          npm test

  test-karma-jasmine-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: npm install, build, and test
        env:
          CI: true
          LISTEN_ADDR: localhost
        run: |
          npm ci
          npm install --no-save karma-jasmine@2.0.1
          npm run build --if-present
          npm test
